'use client';
import { useState, type PointerEvent } from 'react';
import { ArrowDown, ArrowUpRight, MoveUpRight, Pause, Play, RotateCcw } from 'lucide-react';
import Sculpture from './sculpture';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { profile, projects } from './portfolio-data';
export default function Portfolio() {
 const [material,setMaterial]=useState(0),[paused,setPaused]=useState(false),[reset,setReset]=useState(0);
 const [selected,setSelected]=useState<number|null>(null);
 const project=selected===null?null:projects[selected];
 const tilt=(event:PointerEvent<HTMLButtonElement>)=>{if(event.pointerType!=='mouse'||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const box=event.currentTarget.getBoundingClientRect();event.currentTarget.style.setProperty('--rx',`${-((event.clientY-box.top)/box.height-.5)*5}deg`);event.currentTarget.style.setProperty('--ry',`${((event.clientX-box.left)/box.width-.5)*5}deg`);};
 return <main>
 <a className="skip-link" href="#ishlar">Loyihalarga o‘tish</a>
 <header className="site-header wrap"><a className="brand" href="#" aria-label={`${profile.name} bosh sahifa`}>{profile.name.toLowerCase()}<span>®</span><span className="brand-caption">INDEPENDENT<br/>{profile.role.toUpperCase()}</span></a><nav aria-label="Asosiy navigatsiya"><a href="#ishlar">Loyihalar <sup>02</sup></a><a href="#haqimda">Men haqimda</a></nav><a className="header-contact" href="#aloqa">Birga yaratamiz <ArrowUpRight size={17}/></a></header>
 <section className="hero wrap" aria-labelledby="hero-title">
 <div className="hero-topline"><span className="eyebrow"><span className="status-dot"/> MUSTAQIL DIZAYN & KOD</span><span className="edition">PORTFOLIO — VOL. 01 / 2026</span></div>
 <div className="hero-type"><h1 id="hero-title">G‘oyadan<br/><span>tashqarida.</span><span className="title-asterisk" aria-hidden="true">✳</span></h1></div>
 <div className="sculpture-stage"><Sculpture material={material} paused={paused} reset={reset}/></div><span className="object-index">FIG. 001 — CHEKSIZ IMKONIYAT</span>
 <div className="hero-bottom"><div className="hero-intro"><p>Dizaynni his qilinadigan,<br/>kodni esa esda qoladigan qilaman.</p><a href="#ishlar" className="pill-button">Ishlarimni ko‘ring <ArrowUpRight size={19}/></a></div><div className="sculpture-controls"><span className="control-caption">TEGINING. AYLANTIRING. HIS QILING.</span><div className="control-bar"><div className="material-picker" role="group" aria-label="3D obyekt materiali">{['Kislota yashil','Suyuq kumush','Infraqizil'].map((name,i)=><button key={name} title={name} aria-label={name} aria-pressed={material===i} className={`swatch swatch-${i} ${material===i?'selected':''}`} onClick={()=>setMaterial(i)}/>)}</div><span className="control-divider"/><button className="icon-button" aria-label={paused?'Animatsiyani yoqish':'Animatsiyani to‘xtatish'} onClick={()=>setPaused(!paused)}>{paused?<Play size={15}/>:<Pause size={15}/>}</button><button className="icon-button" aria-label="3D ko‘rinishni tiklash" onClick={()=>setReset(r=>r+1)}><RotateCcw size={15}/></button></div></div></div>
 <div className="hero-foot"><a href="#ishlar"><ArrowDown size={15}/> PASTDA YANA KO‘PROQ</a><span>EST. 2026 <span className="small-star">✳</span> BUILT TO FEEL DIFFERENT</span></div>
 </section>
 <div className="discipline-strip" aria-label="Yo‘nalishlar"><div><span>CREATIVE DEVELOPMENT</span><span>✳</span><span>INTERACTIVE DESIGN</span><span>✳</span><span>3D EXPERIENCES</span><span>✳</span><span>DIGITAL EXPERIMENTS</span><span>✳</span></div></div>
 <section id="ishlar" className="work-section wrap"><div className="section-heading"><div><span className="eyebrow">01 / KONSEPT LOYIHALAR</span><h2>Har bir ish —<br/><em>yangi olam.</em></h2></div><p>G‘oya, vizual va texnologiya<br/>uchrashgan joydagi tajribalar.</p></div><div className="projects-grid">{projects.map((item,i)=><article key={item.id} className={`project-card project-${i}`}><button className="project-art" aria-label={`${item.title} loyihasini ko‘rish`} onPointerMove={tilt} onPointerLeave={e=>{e.currentTarget.style.setProperty('--rx','0deg');e.currentTarget.style.setProperty('--ry','0deg');}} onClick={()=>setSelected(i)}><img src={item.image} width={1536} height={1024} alt={item.alt} loading="lazy"/><span className="art-top"><span>EXPERIMENT {item.id}</span><span>{item.year}</span></span><span className="art-title">{item.title}<small>{item.subtitle}</small></span><span className="project-open"><ArrowUpRight size={24}/></span></button><div className="project-info"><div><span className="project-number">/{item.id}</span><h3>{item.title.charAt(0)+item.title.slice(1).toLowerCase()}</h3><span className="project-category">{item.category}</span></div><div className="project-tags">{item.tags.map(tag=><span key={tag}>{tag}</span>)}</div></div></article>)}</div><p className="work-note"><span>✳</span> Mustaqil konseptlar. Doim izlanishda, doim yangi shaklda.</p></section>
 <section id="haqimda" className="about-section wrap"><div className="about-left"><span className="eyebrow">02 / MEN HAQIMDA</span><h2>Chiroyli ko‘rinadi.<br/><em>Yaxshi ishlaydi.</em></h2><div className="signature">zur<span>✳</span></div></div><div className="about-right"><p>Men dizayn va dasturlash o‘rtasida ijod qilaman. Maqsadim — g‘oyalarni o‘ziga xos, qulay va esda qoladigan raqamli tajribalarga aylantirish.</p><p className="about-secondary">Har bir detalning sababi bor. Har bir harakatning ma’nosi. Men uchun yaxshi sayt — ko‘rish bilan birga his qilish mumkin bo‘lgan tajriba.</p><div className="expertise">{[['01','Kreativ dasturlash','Interaktiv saytlar va tajribalar'],['02','Raqamli dizayn','G‘oyadan qulay interfeysgacha'],['03','3D & harakat','Ekranga chuqurlik va hayot']].map(([n,t,d])=><div key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div><ArrowUpRight size={19}/></div>)}</div></div></section>
 <section id="aloqa" className="contact-section wrap"><span className="eyebrow">03 / KEYINGI G‘OYA SIZNIKI</span><h2>Keling, birga<br/><em>farq yarataylik.</em> <MoveUpRight/></h2><div className="contact-bottom"><p>Katta g‘oya bormi?<br/>Uni birga yangi bosqichga olib chiqamiz.</p>{profile.email?<a className="pill-button" href={`mailto:${profile.email}`}>{profile.email}<ArrowUpRight size={19}/></a>:<span className="contact-pending">Aloqa manzili hali qo‘shilmagan.</span>}{profile.telegram&&<a className="telegram-link" href={profile.telegram} target="_blank" rel="noreferrer">Telegram <ArrowUpRight size={16}/></a>}</div></section>
 <footer className="site-footer wrap"><a className="brand" href="#">{profile.name.toLowerCase()}<span>®</span></a><span>© 2026 {profile.name}. G‘oyalar chegarasiz.</span><a href="#">Yuqoriga <ArrowUpRight size={16}/></a></footer>
 <Dialog open={selected!==null} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent className="project-dialog">{project&&<><img className="dialog-art" src={project.image} alt={project.alt} width={1536} height={1024}/><div className="dialog-body"><div className="eyebrow">KONSEPT / {project.year} / {project.category}</div><DialogTitle className="dialog-title">{project.title}</DialogTitle><DialogDescription className="dialog-intro">{project.intro}</DialogDescription><div className="case-columns"><div><h4>G‘oya</h4><p>{project.idea}</p></div><div><h4>Yondashuv</h4><p>{project.approach}</p></div></div><p className="concept-note">Mustaqil vizual konsept. Namuna sifatida ko‘rsatilgan.</p></div></>}</DialogContent></Dialog>
 </main>;
}
