'use client';
import { useEffect, useRef, useState } from 'react';
/* oxlint-disable next/no-img-element -- Static local avatar; no image server is needed. */
type Game = ReturnType<typeof import('./world.js').createWorld>;
type GameTool = {name:string;description:string;inputSchema:object;execute:(input:unknown)=>unknown;annotations?:object};
type ModelContext = {registerTool:(tool:GameTool,options:{signal:AbortSignal})=>void|Promise<void>};
import { MapPin, Pause, Play, Volume2, VolumeX, RotateCcw, Maximize, ArrowUpRight, Car, Footprints, X } from 'lucide-react';

export default function Home() {
 const mount=useRef<HTMLDivElement>(null), api=useRef<Game|null>(null);
 const [ready,setReady]=useState(false),[error,setError]=useState(''),[paused,setPaused]=useState(false),[map,setMap]=useState(false),[muted,setMuted]=useState(true);
 const [hud,setHud]=useState({speed:0,cash:250,mission:0,distance:0,driving:false,nearCar:false,district:'Palm District',message:'',time:'18:42'});
 useEffect(()=>{let cleanup: (()=>void)|undefined,active=true; import('./world.js').then(({createWorld})=>{if(!active||!mount.current)return;try{api.current=createWorld(mount.current,setHud);cleanup=api.current.dispose;setReady(true)}catch(e){console.error(e);setError('3D graphics could not start. Enable hardware acceleration in your browser and reload.')}}).catch(()=>setError('The game could not load. Please reload to try again.'));return()=>{active=false;cleanup?.()}},[]);
 useEffect(()=>{api.current?.pause(paused||map)},[paused,map,ready]);
 useEffect(()=>{if(!ready)return;const context=(document as Document & {modelContext?:ModelContext}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tools=[{name:'set_game_paused',description:'Pause or resume the open-world game.',inputSchema:{type:'object',properties:{paused:{type:'boolean'}},required:['paused'],additionalProperties:false},execute:(input:unknown)=>{if(typeof input!=='object'||input===null||!('paused' in input)||typeof input.paused!=='boolean'||Object.keys(input).some(k=>k!=='paused'))throw new Error('A paused boolean is required.');api.current?.pause(input.paused);setPaused(input.paused);setMap(false);return {paused:input.paused}}},{name:'recover_to_safe_street',description:'Return the character or current car to the starting street.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:(input:unknown)=>{if(typeof input!=='object'||input===null||Array.isArray(input)||Object.keys(input).length)throw new Error('No arguments are accepted.');api.current?.recover();return {location:'Palm District'}}}];for(const tool of tools){try{Promise.resolve(context.registerTool({...tool,annotations:{readOnlyHint:false,untrustedContentHint:false}},{signal:lifecycle.signal})).catch(console.warn)}catch(e){console.warn(e)}}return()=>lifecycle.abort()},[ready]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.repeat)return;if(e.code==='Escape'){setMap(false);setPaused(v=>!v)}if(e.code==='KeyM')setMap(v=>!v)};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 const missions=[['A fresh start','Your ride is waiting. Find the turquoise coupe.','GET IN YOUR CAR'],['Ocean drive','Take the coastal boulevard to the waterfront.','DRIVE TO THE WATERFRONT'],['Chasing the sunset','Follow the coast south to the lighthouse.','REACH THE LIGHTHOUSE'],['Back to the neighborhood','Bring your ride home to Palm District.','RETURN TO PALM DISTRICT'],['The city is yours','Cruise the streets. Find your own way.','FREE ROAM']];
 const mission=missions[Math.min(hud.mission,4)];
 return <main className="game-shell">
 <div ref={mount} className="world" aria-label="3D open world. WASD to move, E to enter a car, drag to look."/><div className="cinematic-shade"/>
 <header className="topbar"><div className="wordmark"><span className="sun-mark">◒</span> SUNSHORE <span className="edition">OPEN WORLD</span></div><div className="top-actions"><span className="session"><i/> FREE ROAM</span><button aria-label={muted?'Enable sound':'Mute sound'} title="Toggle sound" onClick={()=>{setMuted(!muted);api.current?.sound(muted)}}>{muted?<VolumeX size={18}/>:<Volume2 size={18}/>}</button><button aria-label="Fullscreen" title="Fullscreen" onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else document.documentElement.requestFullscreen?.().catch(()=>{})}}><Maximize size={18}/></button><button aria-label="Pause game" title="Pause game" onClick={()=>setPaused(true)}><Pause size={18}/></button></div></header>
 <aside className="mission-panel"><div className="eyebrow"><span className="yellow-line"/>{hud.mission>=4?'EXPLORATION':`STORY MISSION 0${hud.mission+1}`}</div><h1>{mission[0]}</h1><p>{mission[1]}</p><div className="objective"><span className="objective-icon"><ArrowUpRight size={17}/></span><span>{mission[2]}</span>{hud.mission<4&&<b>{hud.distance} m</b>}</div></aside>
 <aside className="player-card"><img src="/character.png" alt="Your custom character" width={48} height={48}/><div><span className="eyebrow">YOUR CHARACTER</span><strong>The newcomer</strong><div className="health"><span/></div></div><span className="cash">${hud.cash.toLocaleString('en-US')}</span></aside>
 <div className="location-title"><span>SAN PALOMA COUNTY</span><h2>{hud.district}</h2><div><i/> {hud.time}<span> / </span>27° CLEAR SKIES</div></div>
 <div className="map-area"><button className="map-button" aria-label="Open city map" onClick={()=>setMap(true)}><canvas id="minimap" width="240" height="190"/><span className="north">N</span><span className="map-expand"><Maximize size={14}/></span></button><div className="map-caption"><MapPin size={13}/>{hud.district}<span><kbd>M</kbd> MAP</span></div></div>
 <div className="interaction">{hud.message&&<output className="toast">{hud.message}</output>}<div className="interact-pill"><kbd>E</kbd>{hud.driving?'Exit vehicle':hud.nearCar?'Enter vehicle':'Find a car to drive'}{hud.driving?<Car size={18}/>:<Footprints size={18}/>}</div></div>
 <div className="speed"><div>{hud.driving?String(hud.speed).padStart(3,'0'):'ON FOOT'}</div><span>{hud.driving?'KM / H':'EXPLORE THE CITY'}</span><div className="speed-bars">{Array.from({length:22},(_,i)=><i key={i} style={{opacity:hud.driving&&i<hud.speed/6?1:.16}}/>)}</div></div>
 <footer className="controls"><span><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> Move / Drive</span><span><kbd>SHIFT</kbd> Sprint / Boost</span><span><kbd>SPACE</kbd> Jump / Brake</span><span>↔ Drag to look</span><span><kbd>R</kbd> Recover</span></footer>
 <div className="touch-controls"><div>{['KeyW','KeyA','KeyS','KeyD'].map((key,i)=><button key={key} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);api.current?.input(key,true)}} onPointerUp={()=>api.current?.input(key,false)} onPointerCancel={()=>api.current?.input(key,false)}>{['↑','←','↓','→'][i]}</button>)}</div><button onClick={()=>api.current?.interact()}>E</button><button onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);api.current?.input('ShiftLeft',true)}} onPointerUp={()=>api.current?.input('ShiftLeft',false)} onPointerCancel={()=>api.current?.input('ShiftLeft',false)}>BOOST</button></div>
 {(!ready||error)&&<div className="loading-screen"><span className="sun-mark">◒</span><h2>SUNSHORE</h2><p>{error||'Finding your place in the city…'}</p>{error&&<button onClick={()=>location.reload()}>Try again</button>}</div>}
 {paused&&<section className="pause-screen"><span className="eyebrow">TAKE A BREATHER</span><h2>City on pause.</h2><p>The next street is yours to discover.</p><button className="primary" onClick={()=>setPaused(false)}><Play size={18}/>Back to the city</button><button onClick={()=>{api.current?.recover();setPaused(false)}}><RotateCcw size={17}/>Return to a safe street</button><span className="pause-note">A playable open-world prototype · Character inspired by your photo</span></section>}
 {map&&<section className="full-map"><header><div><span className="eyebrow">SAN PALOMA COUNTY</span><h2>Your city. Your route.</h2></div><button aria-label="Close map" onClick={()=>setMap(false)}><X/></button></header><canvas ref={c=>{if(c)api.current?.drawMap(c,true)}} width="800" height="650"/><footer><span><i className="legend-player"/>You</span><span><i className="legend-mission"/>Mission</span><span><i className="legend-car"/>Vehicle</span><span>Press M to return</span></footer></section>}
 </main>
}

