'use client';
import { useEffect, useRef, useState, type CSSProperties, type FormEvent } from 'react';
import { ArrowRight, ArrowUpRight, Check, ChevronRight, Coffee, CookingPot, Minus, Plus, Send, ShoppingBag, Utensils, RotateCcw, Globe2, Sparkles, LayoutDashboard, PackageCheck, Truck, CircleCheck, Circle, Clock3 } from 'lucide-react';

const menu=[{name:'Margherita',note:'Pomidor · mozzarella · rayhon',price:48000,Icon:Utensils},{name:'Pasta Alfredo',note:'Qaymoqli sous · tovuq',price:42000,Icon:CookingPot},{name:'Limonad',note:'Limon · yalpiz · muz',price:18000,Icon:Coffee}];
const money=(value:number)=>new Intl.NumberFormat('uz-UZ').format(value);
export function RestaurantDemo(){
 const [quantities,setQuantities]=useState([0,0,0]),[step,setStep]=useState(0);
 const total=quantities.reduce((sum,q,i)=>sum+q*menu[i].price,0),count=quantities.reduce((a,b)=>a+b,0);
 useEffect(()=>{if(step>0&&step<4){const timer=setTimeout(()=>setStep(s=>s+1),1500);return()=>clearTimeout(timer)}},[step]);
 const reset=()=>{setStep(0);setQuantities([0,0,0])};
 const statuses=['Qabul qilindi','Tayyorlanmoqda','Yetkazilmoqda','Yakunlandi'];
 return <div className="restaurant-demo"><header className="restaurant-header"><span className="resto-logo">pesto<span>®</span></span><span className="restaurant-tag">YAXSHI TA’M. BIR TEGINISH.</span><button className="demo-reset" onClick={reset} title="Demoni qayta boshlash" aria-label="Restoran demosini qayta boshlash"><RotateCcw size={15}/></button></header>{step===0?<><div className="menu-heading"><h4>Bugun nima yeymiz?</h4><span><ShoppingBag size={16}/>{count}</span></div><div className="menu-items">{menu.map((item,i)=>{const Icon=item.Icon;return <div className="menu-item" key={item.name}><div className={`food-icon food-${i}`}><Icon size={26}/></div><div className="menu-item-copy"><h5>{item.name}</h5><p>{item.note}</p><strong>{money(item.price)} <small>so‘m</small></strong></div><div className="quantity-controls"><button disabled={!quantities[i]} aria-label={`${item.name} sonini kamaytirish`} onClick={()=>setQuantities(q=>q.map((v,n)=>n===i?Math.max(0,v-1):v))}><Minus size={14}/></button><span aria-label={`${item.name} soni`}>{quantities[i]}</span><button disabled={quantities[i]>=9} aria-label={`${item.name} qo‘shish`} onClick={()=>setQuantities(q=>q.map((v,n)=>n===i?Math.min(9,v+1):v))}><Plus size={14}/></button></div></div>})}</div><div className="cart-footer"><div aria-live="polite"><span>Jami</span><strong>{money(total)} <small>so‘m</small></strong></div><button className="demo-primary" disabled={!count} onClick={()=>setStep(1)}>Buyurtmani sinash <ArrowRight size={16}/></button></div></>:<div className="order-progress"><div className={`order-orb ${step===4?'complete':''}`}>{step===4?<Check size={35}/>:step===3?<Truck size={35}/>:step===2?<CookingPot size={35}/>:<PackageCheck size={35}/>}</div><span className="mono">DEMO BUYURTMA / #001</span><h4 role="status">{statuses[step-1]}{step<4?'…':'!'}</h4><p>{count} ta mahsulot · {money(total)} so‘m</p><div className="order-steps">{statuses.map((status,i)=><span key={status} className={i<step?'done':''}><i>{i<step?<Check size={11}/>:i+1}</i><small>{status}</small></span>)}</div><button className="demo-primary" onClick={reset}>{step===4?'Yana sinab ko‘rish':'Qayta boshlash'}<RotateCcw size={15}/></button></div>}<div className="demo-microcopy">Demo menyu va narxlar. Haqiqiy buyurtma yaratilmaydi.</div></div>;
}

type Message={role:'bot'|'user';text:string};
const initialMessages:Message[]=[{role:'bot',text:'Salom! Men biznes yordamchisiman 👋 Sizga qanday yordam bera olaman?'},{role:'bot',text:'Quyidagi tugmalardan birini tanlang yoki xabar yozing.'}];
export function TelegramDemo(){
 const [messages,setMessages]=useState<Message[]>(initialMessages),[input,setInput]=useState(''),[typing,setTyping]=useState(false);
 const timer=useRef<ReturnType<typeof setTimeout>|null>(null),chat=useRef<HTMLDivElement>(null);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
 useEffect(()=>{if(chat.current)chat.current.scrollTop=chat.current.scrollHeight},[messages,typing]);
 const send=(text:string)=>{if(!text.trim()||typing)return;const value=text.trim().slice(0,240);setMessages(m=>[...m.slice(-11),{role:'user',text:value}]);setInput('');setTyping(true);timer.current=setTimeout(()=>{const q=value.toLowerCase();const reply=/buyurt|menyu|ovqat/.test(q)?'🍽 Menyu, savat va to‘lov — hammasi bot ichida. Restoran demosida buyurtma oqimini sinab ko‘ring.':/xizmat|nima|narx/.test(q)?'⚡ Buyurtmalar, avtomatik javoblar, to‘lovlar va admin bilan bog‘lanish. Bot biznesingizga mos quriladi.':/operator|aloqa|abubakr|telefon/.test(q)?'💬 Loyihangizni Abubakr bilan muhokama qiling: +998 97 400 98 77. Pastdagi aloqa bo‘limida qo‘ng‘iroq qilishingiz mumkin.':/salom|hello|start/.test(q)?'Salom! 👋 Buyurtma, xizmatlar yoki operator haqida yozing. Men demoda qanday ishlashimni ko‘rsataman.':'Xabaringizni tushundim ✨ Haqiqiy botda sizning biznes qoidalaringiz, katalogingiz va kerakli integratsiyalaringiz ishlaydi. Demoda “Xizmatlar”ni tanlab ko‘ring.';setMessages(m=>[...m,{role:'bot',text:reply}]);setTyping(false)},650);};
 const submit=(e:FormEvent)=>{e.preventDefault();send(input)};
 const reset=()=>{if(timer.current)clearTimeout(timer.current);setMessages(initialMessages);setTyping(false);setInput('')};
 return <div className="telegram-demo"><header className="bot-header"><span className="bot-avatar"><Send size={21}/></span><div><h4>Business Assistant</h4><span>Demo bot · har doim tayyor</span></div><button className="demo-reset" onClick={reset} aria-label="Bot demosini qayta boshlash"><RotateCcw size={15}/></button></header><div className="chat-messages" ref={chat} role="log" aria-label="Demo bot bilan suhbat" aria-live="polite">{messages.map((m,i)=><div key={i} className={`chat-message ${m.role}`}><span>{m.text}</span><small>{m.role==='bot'?'BOT':'SIZ'} <Check size={11}/></small></div>)}{typing&&<div className="chat-message bot typing">Javob yozilmoqda<span>···</span></div>}</div><div className="quick-replies">{['🍽 Buyurtma berish','⚡ Xizmatlar','💬 Operator'].map(t=><button key={t} disabled={typing} onClick={()=>send(t)}>{t}</button>)}</div><form className="chat-input" onSubmit={submit}><label className="sr-only" htmlFor="bot-message">Botga xabar</label><input id="bot-message" value={input} maxLength={240} onChange={e=>setInput(e.target.value)} placeholder="Xabar yozing…" autoComplete="off"/><button type="submit" disabled={!input.trim()||typing} aria-label="Demo botga xabar yuborish"><Send size={19}/></button></form><div className="demo-microcopy">Simulyatsiya. Telegram orqali xabar yuborilmaydi.</div></div>;
}

const themes=[{name:'Midnight',bg:'#17181d',ink:'#f3f1eb',accent:'#bce78b'},{name:'Paper',bg:'#f2f0e9',ink:'#23231f',accent:'#e76d48'},{name:'Electric',bg:'#4233b2',ink:'#ffffff',accent:'#d9fc88'}];
export function WebsiteDemo(){
 const [theme,setTheme]=useState(0),[works,setWorks]=useState(false);
 const t=themes[theme];
 return <div className="website-demo"><div className="website-toolbar"><span>Bir brend. Uch xarakter.</span><div role="group" aria-label="Sayt rang uslubi">{themes.map((item,i)=><button key={item.name} aria-label={`${item.name} mavzusi`} aria-pressed={theme===i} onClick={()=>setTheme(i)} style={{'--swatch':item.accent} as CSSProperties}>{theme===i&&<Check size={13}/>}</button>)}</div></div><div className="mini-website" style={{'--preview-bg':t.bg,'--preview-ink':t.ink,'--preview-accent':t.accent} as CSSProperties}><div className="mini-site-nav"><strong>form<span>®</span></strong><span>DESIGN FOR WHAT’S NEXT</span><span className="mini-site-star">✳</span></div>{!works?<div className="mini-site-hero"><span className="mini-eyebrow">YOUR BRAND. YOUR RULES.</span><h4>Oddiy emas.<br/><em>O‘zingizdek.</em></h4><p>Xarakteri bor brendlar uchun<br/>esda qoladigan raqamli tajriba.</p><button onClick={()=>setWorks(true)}>Loyihalarni ko‘rish <ArrowUpRight size={17}/></button><span className="mini-large-star" aria-hidden="true">✳</span></div>:<div className="mini-site-works"><span className="mini-eyebrow">SELECTED WORK / 03</span><h4>G‘oyalar amalda.</h4>{['Brend identiteti','Raqamli tajriba','Yangi platforma'].map((name,i)=><div key={name}><span>0{i+1}</span><strong>{name}</strong><ArrowUpRight size={17}/></div>)}<button onClick={()=>setWorks(false)}>← Bosh sahifa</button></div>}<div className="mini-site-footer"><span>BUILT TO BE REMEMBERED</span><span>© FORM STUDIO</span></div></div><div className="website-theme-label"><span><Globe2 size={14}/>{t.name} uslubi</span><span>Rangni almashtiring ↑</span></div></div>;
}

const columns=['Yangi','Jarayonda','Tayyor'];
const tasks=[{name:'Yangi buyurtmalar',detail:'Buyurtmalarni ko‘rib chiqish',initial:0},{name:'Mijoz bilan aloqa',detail:'Talablarni aniqlashtirish',initial:1},{name:'Hisobot tayyorlash',detail:'Natijalarni jamlash',initial:0}];
export function SystemDemo(){
 const [stages,setStages]=useState(tasks.map(t=>t.initial));
 const done=stages.filter(s=>s===2).length;
 return <div className="system-demo"><div className="system-header"><div><span className="system-logo"><LayoutDashboard size={17}/></span><h4>Business OS<span>WORKSPACE</span></h4></div><button className="demo-reset" onClick={()=>setStages(tasks.map(t=>t.initial))} aria-label="Tizim demosini qayta boshlash"><RotateCcw size={15}/></button></div><div className="system-stats"><div><span>Vazifalar</span><strong>03</strong><small>Barchasi bir joyda</small></div><div><span>Jarayonda</span><strong>{String(stages.filter(s=>s===1).length).padStart(2,'0')}</strong><small>Faol ishlar</small></div><div><span>Yakunlangan</span><strong>{String(done).padStart(2,'0')}</strong><small>{Math.round(done/3*100)}% bajarildi</small></div></div><div className="workflow-title"><h5>Ish oqimi</h5><span>Vazifani keyingi bosqichga o‘tkazing</span></div><div className="workflow-list">{tasks.map((task,i)=><div className={`workflow-task task-stage-${stages[i]}`} key={task.name}><span className="task-status-icon">{stages[i]===2?<CircleCheck size={20}/>:stages[i]===1?<Clock3 size={20}/>:<Circle size={20}/>}</span><div><h6>{task.name}</h6><p>{task.detail}</p></div><button onClick={()=>setStages(s=>s.map((v,n)=>n===i?(v+1)%3:v))} aria-label={`${task.name}: ${columns[(stages[i]+1)%3]} bosqichiga o‘tkazish`}><span>{columns[stages[i]]}</span><ChevronRight size={15}/></button></div>)}</div><div className="system-progress"><span role="status">{done===3?'Barcha demo vazifalar bajarildi!':`${done} / 3 vazifa bajarildi`}</span><div><i style={{width:`${done/3*100}%`}}/></div></div><div className="demo-microcopy">Namuna ma’lumotlar. O‘zgarishlar faqat shu demoda.</div></div>;
}
