import * as THREE from 'three';

export function createWorld(container, onHud) {
 const scene=new THREE.Scene(); scene.background=new THREE.Color('#c8dce0'); scene.fog=new THREE.FogExp2('#cfdddc',.0028);
 const camera=new THREE.PerspectiveCamera(58,1,.1,1800);
 const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.6)); renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
 renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;container.appendChild(renderer.domElement);
 const ambient=new THREE.HemisphereLight('#d9efff','#827c51',2.0);scene.add(ambient);
 const sun=new THREE.DirectionalLight('#ffdfac',3.3);sun.position.set(-90,105,-110);sun.castShadow=true;
 sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-95;sun.shadow.camera.right=95;sun.shadow.camera.top=95;sun.shadow.camera.bottom=-95;sun.shadow.camera.far=420;sun.shadow.normalBias=.035;sun.shadow.bias=-.0003;scene.add(sun,sun.target);
 let seed=921;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
 const materials=new Map(),batches=new Map(),geometries=new Map(),colliders=[],cars=[],people=[];
 const mat=(color,metal=0,rough=.8)=>{const key=color+','+metal+','+rough;if(!materials.has(key))materials.set(key,new THREE.MeshStandardMaterial({color,metalness:metal,roughness:rough}));return materials.get(key)};
 const geo=(type)=>{if(!geometries.has(type))geometries.set(type,type==='box'?new THREE.BoxGeometry(1,1,1):type==='sphere'?new THREE.SphereGeometry(1,12,10):type==='cylinder'?new THREE.CylinderGeometry(1,1,1,10):type==='cone'?new THREE.ConeGeometry(1,1,7):new THREE.PlaneGeometry(1,1));return geometries.get(type)};
 const dummy=new THREE.Object3D();
 function staticMesh(type,m,x,y,z,sx,sy,sz,rx=0,ry=0,rz=0){const key=type+':'+m.uuid;if(!batches.has(key))batches.set(key,{type,m,items:[]});dummy.position.set(x,y,z);dummy.scale.set(sx,sy,sz);dummy.rotation.set(rx,ry,rz);dummy.updateMatrix();batches.get(key).items.push(dummy.matrix.clone())}
 const box=(m,x,y,z,w,h,d,ry=0)=>staticMesh('box',m,x,y,z,w,h,d,0,ry);
 function part(parent,type,m,x,y,z,sx,sy,sz,rx=0,ry=0,rz=0){const mesh=new THREE.Mesh(geo(type),m);mesh.position.set(x,y,z);mesh.scale.set(sx,sy,sz);mesh.rotation.set(rx,ry,rz);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh}
 function sign(text,color,bg,w,h,x,y,z,rotation=0,parent=scene){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle=bg;ctx.fillRect(0,0,512,128);ctx.fillStyle=color;ctx.font='bold 53px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,256,68,480);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshStandardMaterial({map:tex,roughness:.8}));mesh.position.set(x,y,z);mesh.rotation.y=rotation;parent.add(mesh);return mesh}
 const asphalt=mat('#4c5456'),sidewalk=mat('#c4c3b5'),curb=mat('#dfded0'),line=mat('#e8dcaa'),white=mat('#e8e6d7'),sand=mat('#c9b992'),grass=mat('#6f8858'),steel=mat('#455152',.5),dark=mat('#25383b'),glass=mat('#577983',.4,.22);
 box(sand,0,-.8,0,540,1.4,540);box(grass,-10,-.04,0,470,.1,500);
 const roads=[-192,-128,-64,0,64,128,192];
 for(const p of roads){box(asphalt,p,.015,0,17,.12,492);box(asphalt,0,.025,p,492,.12,17);
  for(const side of [-1,1]){box(sidewalk,p+side*10,.14,0,3.5,.35,492);box(sidewalk,0,.14,p+side*10,492,.35,3.5);box(curb,p+side*8.5,.25,0,.3,.4,492);box(curb,0,.25,p+side*8.5,492,.4,.3)}
  for(let q=-240;q<=240;q+=8){if(roads.some(r=>Math.abs(q-r)<12))continue;box(line,p-.19,.095,q,.13,.018,4.2);box(line,p+.19,.095,q,.13,.018,4.2);box(line,q,.105,p-.19,4.2,.018,.13);box(line,q,.105,p+.19,4.2,.018,.13)}
 }
 for(const x of roads)for(const z of roads){for(const s of [-1,1])for(let j=-6;j<7;j+=2){box(white,x+j,.11,z+s*10,1.1,.02,3);box(white,x+s*10,.11,z+j,3,.02,1.1)}}
 function palm(x,z,h=10){const bark=mat('#85745b');staticMesh('cylinder',bark,x,h/2,z,.23,h,.23,0,0,-.045);for(let i=0;i<8;i++){const a=i*Math.PI/4+rand()*.3;const leafMat=mat(i%2?'#647949':'#4f733f');for(let j=0;j<5;j++){const r=.7+j*.66,y=h+Math.sin(j/4*Math.PI)*1.1-j*.23;staticMesh('sphere',leafMat,x+Math.sin(a)*r,y,z+Math.cos(a)*r,.35,.08,1.05,.18+j*.11,a)}}staticMesh('sphere',mat('#6d7044'),x,h,z,.5,.45,.5)}
 function streetlight(x,z,a=0){box(steel,x,4.3,z,.11,8.6,.11);box(steel,x+Math.sin(a)*.6,8.5,z+Math.cos(a)*.6,.1,.12,1.5,a);box(mat('#f7ecc7'),x+Math.sin(a)*1.1,8.45,z+Math.cos(a)*1.1,.5,.12,.75,a)}
 for(const x of [-192,-64,0,128,192])for(let z=-221;z<240;z+=26){if(roads.some(r=>Math.abs(z-r)<13))continue;palm(x+12.5,z,8+rand()*5);if(x!==0)palm(x-12.5,z,9+rand()*4);streetlight(x-8.8,z,Math.PI/2)}
 const palette=['#d1bba1','#d3c9b2','#aebbb8','#b9a58f','#dfd8c1','#d4b6a0','#9ba9a9'];
 const facadeCache=new Map();
 function facade(color){if(facadeCache.has(color))return facadeCache.get(color);const c=document.createElement('canvas');c.width=256;c.height=256;const t=c.getContext('2d');t.fillStyle=color;t.fillRect(0,0,256,256);for(let i=0;i<2800;i++){t.fillStyle=rand()>.5?'#ffffff0c':'#0000000b';t.fillRect(rand()*256,rand()*256,1+rand()*3,1+rand()*3)}for(let y=12;y<256;y+=64)for(let x=14;x<256;x+=64){t.fillStyle='#e0d8c4';t.fillRect(x-3,y-3,39,45);t.fillStyle=rand()>.22?'#4b666c':'#a3a698';t.fillRect(x,y,33,38);t.fillStyle='#b3bdb5';t.fillRect(x+15,y,2,38);t.fillRect(x,y+18,33,2);t.fillStyle='#00000030';t.fillRect(x-3,y+40,40,4)}const tx=new THREE.CanvasTexture(c);tx.colorSpace=THREE.SRGBColorSpace;tx.wrapS=tx.wrapT=THREE.RepeatWrapping;const m=new THREE.MeshStandardMaterial({map:tx,roughness:.88});facadeCache.set(color,m);return m}
 const shopNames=['PALOMA MARKET','SUNSET RECORDS','PACIFIC MOTEL','COAST COFFEE','AUTO SERVICE','LA ESQUINA','PALM LAUNDRY','SURF & SUPPLY'];let shop=0;
 for(let ix=0;ix<6;ix++)for(let iz=0;iz<6;iz++){
  const cx=-160+ix*64,cz=-160+iz*64;
  if((ix===4&&iz===3)||(ix===5&&iz===1)){box(grass,cx,.2,cz,43,.5,43);box(sidewalk,cx,.5,cz,3,.1,40);box(sidewalk,cx,.5,cz,40,.1,3);for(let j=0;j<6;j++)palm(cx-17+rand()*34,cz-17+rand()*34,7+rand()*3);continue}
  for(let a=0;a<2;a++)for(let b=0;b<2;b++){
   const x=cx+(a-.5)*23,z=cz+(b-.5)*23,w=18+rand()*3,d=18+rand()*3;const downtown=ix<3&&iz<3;const h=downtown?18+Math.floor(rand()*9)*5:5+Math.floor(rand()*4)*3.5;const color=palette[Math.floor(rand()*palette.length)];
   box(facade(color),x,h/2+.3,z,w,h,d);colliders.push({x,z,w:w/2+.5,d:d/2+.5});
   box(curb,x,h+.4,z,w+.4,.6,d+.4);box(mat('#8a9190'),x,h+.75,z,w-.5,.2,d-.5);
   for(let n=0;n<2;n++){box(steel,x-4+n*7,h+1.25,z+2,2,1,2);box(dark,x-4+n*7,h+1.77,z+2,1.6,.06,1.6)}
   if(h<21){const front=z+d/2+.05;box(glass,x,1.9,front,w-1.5,2.8,.08);for(let k=-1;k<=1;k++)box(curb,x+k*w/3,1.7,front+.05,.14,3.2,.18);box(mat(shop%2?'#b6664f':'#438981'),x,3.6,front+.7,w+.3,.25,1.6);if(shop<34)sign(shopNames[shop%8],'#f6edcf',shop%2?'#8b4e3e':'#2e6762',w-1,1.05,x,4.5,front+.1);shop++;
    if(rand()>.5){for(let fl=1;fl<Math.floor(h/3.5);fl++){box(sidewalk,x,fl*3.5+2.1,front+.7,w,.13,1.4);box(steel,x,fl*3.5+3,front+1.3,w,.09,.07);for(let k=-8;k<9;k+=2)box(steel,x+k,fl*3.5+2.6,front+1.3,.045,.85,.045)}}
   }
  }
 }
 // Waterfront: a broad promenade, sand and animated ocean.
 box(sidewalk,226,.2,0,22,.5,500);box(sand,251,-.05,0,28,.3,620);box(curb,235,.6,0,.7,1.2,500);
 for(let z=-230;z<240;z+=22){palm(222,z,10+rand()*3);box(steel,234,1.2,z,.07,1.2,.07);box(steel,234,1.7,z,.1,.08,22)}
 for(let z=-210;z<230;z+=42){box(mat('#936e4c'),229,.9,z,1.1,.18,3);box(mat('#936e4c'),229.45,1.3,z,.14,.8,3);box(steel,229,.5,z-1,.8,.8,.1);box(steel,229,.5,z+1,.8,.8,.1)}
 const waterMat=new THREE.ShaderMaterial({uniforms:{time:{value:0},sunColor:{value:new THREE.Color('#c8e0d0')}},vertexShader:'varying vec3 vP; uniform float time; void main(){vec3 p=position;p.z+=sin(p.x*.1+time)*.17+cos(p.y*.07+time*.7)*.22;vP=p;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);}',fragmentShader:'varying vec3 vP;uniform float time;void main(){float wave=sin(vP.x*.17+vP.y*.3+time)*sin(vP.y*.23-time);float glint=pow(max(0.,wave),13.);vec3 col=mix(vec3(.15,.45,.49),vec3(.4,.66,.65),wave*.3+.4);col+=vec3(.8,.72,.5)*glint*.45;gl_FragColor=vec4(col,1.);}'});
 const water=new THREE.Mesh(new THREE.PlaneGeometry(1500,2000,80,80),waterMat);water.rotation.x=-Math.PI/2;water.position.set(1010,-.2,0);scene.add(water);
 // Distant foothills and a coastal beacon.
 for(let i=0;i<24;i++){staticMesh('cone',mat(i%2?'#87999a':'#9eaaa4'),-500+i*45,30+rand()*25,-390-rand()*100,65+rand()*85,100+rand()*130,65+rand()*70)}
 staticMesh('cylinder',white,220,10,165,3.2,20,3.2);for(let y=5;y<20;y+=7)staticMesh('cylinder',mat('#ba6a4f'),220,y,165,3.23,2,3.23);staticMesh('cylinder',dark,220,21,165,4.2,.5,4.2);staticMesh('cylinder',glass,220,22.5,165,2.7,3,2.7);staticMesh('cone',mat('#596d68'),220,25,165,4,2,4);box(sidewalk,220,.1,165,20,.5,20);colliders.push({x:220,z:165,w:3.6,d:3.6});
 // Street furniture and cross-street signals.
 for(let x=-192;x<193;x+=64)for(let z=-192;z<193;z+=64){if(rand()<.6){box(steel,x+9,2.8,z+9,.13,5.6,.13);box(dark,x+9,5,z+9,.5,1.3,.45);box(mat('#cf8760'),x+9,5.35,z+9.24,.2,.2,.03);box(mat('#afca86'),x+9,4.75,z+9.24,.2,.2,.03)} }
 for(let i=0;i<40;i++){const x=roads[Math.floor(rand()*7)]+10.5,z=-232+rand()*464;if(roads.some(r=>Math.abs(r-z)<12))continue;box(mat('#66796c'),x,.6,z,.65,1.1,.65);box(steel,x,1.18,z,.7,.12,.7)}
 // A sky dome with a low warm horizon.
 const sky=new THREE.Mesh(new THREE.SphereGeometry(1200,32,20),new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{top:{value:new THREE.Color('#71a3bc')},bottom:{value:new THREE.Color('#f0d5b4')}},vertexShader:'varying vec3 vP;void main(){vP=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec3 vP;uniform vec3 top;uniform vec3 bottom;void main(){float h=clamp(normalize(vP).y,0.,1.);gl_FragColor=vec4(mix(bottom,top,pow(h,.45)),1.);}'}));scene.add(sky);
 const sunDisc=new THREE.Mesh(new THREE.SphereGeometry(18,24,16),new THREE.MeshBasicMaterial({color:'#fff1cf',fog:false}));sunDisc.position.set(-620,180,-720);scene.add(sunDisc);
 for(const {type,m,items} of batches.values()){const mesh=new THREE.InstancedMesh(geo(type),m,items.length);items.forEach((matrix,i)=>mesh.setMatrixAt(i,matrix));mesh.castShadow=true;mesh.receiveShadow=true;mesh.computeBoundingSphere();scene.add(mesh)}
 batches.clear();
 function createCar(x,z,color,heading=0,traffic=false){const g=new THREE.Group();const paint=mat(color,.48,.28),rubber=mat('#1c2428'),chrome=mat('#bbc7c5',.85,.2);g.position.set(x,.08,z);g.rotation.y=heading;
  part(g,'box',paint,0,.73,0,2.1,.7,4.65);part(g,'box',paint,0,.96,-1.5,2.06,.3,1.5);part(g,'box',glass,0,1.37,.08,1.82,.67,2.25);part(g,'box',paint,0,1.75,.12,1.9,.12,2.35);
  for(const s of [-1,1]){part(g,'box',paint,s*.94,1.39,0,.1,.75,.12);part(g,'box',paint,s*.94,1.39,1.07,.1,.75,.13);part(g,'box',paint,s*.94,1.39,-.99,.1,.75,.13);part(g,'box',paint,s*1.16,1.24,-.72,.3,.18,.42);part(g,'box',chrome,s*1.065,.96,.45,.035,.055,.27);part(g,'box',chrome,s*.72,.85,-2.34,.49,.25,.04);part(g,'box',mat('#fdf0c2'),s*.72,.85,-2.37,.43,.21,.04);part(g,'box',mat('#c55742'),s*.73,.86,2.34,.5,.2,.04)}
  part(g,'box',chrome,0,.5,-2.38,2,.14,.13);part(g,'box',chrome,0,.5,2.38,2,.14,.13);part(g,'box',dark,0,.76,-2.35,.65,.21,.03);part(g,'box',white,0,.62,2.46,.55,.16,.02);
  const wheels=[];for(const a of [-1,1])for(const b of [-1,1]){wheels.push(part(g,'cylinder',rubber,a*1.03,.47,b*1.4,.43,.26,.43,0,0,Math.PI/2));part(g,'cylinder',chrome,a*1.18,.47,b*1.4,.24,.03,.24,0,0,Math.PI/2)}
  scene.add(g);const c={g,speed:0,wheels,traffic,phase:rand()*1000};cars.push(c);return c;
 }
 createCar(4,23,'#55a8a4',0);
 for(let i=0;i<20;i++){const x=roads[Math.floor(rand()*7)]+(i%2?5.8:-5.8),z=-210+rand()*420;if(Math.abs(x-4)<3&&Math.abs(z-23)<10)continue;createCar(x,z,['#e4d8b9','#aa6357','#507c91','#c9a65e','#6b7d70','#77748a'][i%6],i%2?0:Math.PI)}
 for(let i=0;i<15;i++){const c=createCar(0,0,['#ad6953','#c2c9c1','#b09a6d','#526e80'][i%4],0,true);c.route=roads[i%7];c.phase=i*32;c.axis=i%2;c.dir=i%3===0?-1:1}
 function person(x,z,custom=false){const g=new THREE.Group(),skin=mat(custom?'#bf916f':'#a78165'),shirt=mat(custom?'#f1ede3':['#b47e68','#719395','#c4b37e','#727d89'][Math.floor(rand()*4)]),pants=mat('#3b4d5d'),shoe=mat('#e3e1d5');
  part(g,'sphere',shirt,0,1.43,0,.38,.5,.22);part(g,'sphere',skin,0,2.03,-.015,.22,.29,.22);part(g,'cylinder',skin,0,1.77,0,.12,.2,.12);
  part(g,'sphere',mat('#322f2b'),0,2.11,.035,.23,.24,.2);part(g,'sphere',skin,0,2.015,-.08,.205,.245,.19);part(g,'sphere',skin,0,2.02,-.272,.052,.075,.06);
  for(const s of [-1,1]){part(g,'sphere',skin,s*.215,2.02,0,.045,.08,.055);part(g,'sphere',mat('#282e2e'),s*.077,2.08,-.246,.023,.015,.011)}
  if(custom){part(g,'sphere',white,0,2.255,0,.244,.14,.23);part(g,'box',white,0,2.2,-.235,.43,.038,.25);sign('Muslim','#2d332f','#eeede3',.22,.07,0,2.25,-.226,0,g).rotation.y=Math.PI;}
  const arms=[],legs=[];for(const s of [-1,1]){const arm=new THREE.Group();arm.position.set(s*.4,1.63,0);part(arm,'sphere',shirt,0,-.12,0,.145,.23,.155);part(arm,'cylinder',skin,0,-.42,0,.085,.43,.085);part(arm,'sphere',skin,0,-.66,0,.095,.12,.075);g.add(arm);arms.push(arm);const leg=new THREE.Group();leg.position.set(s*.17,1.08,0);part(leg,'cylinder',pants,0,-.45,0,.137,.91,.137);part(leg,'box',shoe,0,-.97,-.06,.26,.16,.43);g.add(leg);legs.push(leg)}
  g.position.set(x,.28,z);scene.add(g);return {g,arms,legs,phase:rand()*10};
 }
 const player=person(6.8,33,true);player.g.rotation.y=0;
 for(let i=0;i<35;i++){const p=person(roads[i%7]+(i%2?10:-10),-220+rand()*440);p.speed=.6+rand()*.7;p.dir=i%2?1:-1;people.push(p)}
 const marker=new THREE.Group();const ring=new THREE.Mesh(new THREE.TorusGeometry(2,.085,8,48),new THREE.MeshBasicMaterial({color:'#f4cc6e'}));ring.rotation.x=-Math.PI/2;marker.add(ring);const beacon=new THREE.Mesh(new THREE.CylinderGeometry(1.95,1.95,7,24,1,true),new THREE.MeshBasicMaterial({color:'#f4cc6e',transparent:true,opacity:.11,side:THREE.DoubleSide,depthWrite:false}));beacon.position.y=3.5;marker.add(beacon);const diamond=new THREE.Mesh(new THREE.OctahedronGeometry(.5),new THREE.MeshStandardMaterial({color:'#ffe196',emissive:'#d89b32',emissiveIntensity:.4}));diamond.position.y=4;marker.add(diamond);scene.add(marker);
 const targets=[new THREE.Vector3(4,.3,23),new THREE.Vector3(192,.3,-128),new THREE.Vector3(192,.3,165),new THREE.Vector3(4,.3,32)];
 let currentCar=null,mission=0,cash=250,paused=false,elapsed=0,lastHud=0,jump=0,vertical=0,yaw=.24,pitch=.22,dragging=false,lastX=0,lastY=0,dragTime=0,toast='',toastUntil=0,frameId,disposed=false;
 const keys=new Set(),lookTarget=new THREE.Vector3(),cameraTarget=new THREE.Vector3();
 camera.position.set(11,5.5,43);lookTarget.copy(player.g.position).add(new THREE.Vector3(0,1.5,0));camera.lookAt(lookTarget);
 function message(text){toast=text;toastUntil=elapsed+4}
 function collision(x,z,r=.5){return Math.abs(x)>244||Math.abs(z)>244||colliders.some(c=>Math.abs(x-c.x)<c.w+r&&Math.abs(z-c.z)<c.d+r)}
 function nearest(){let closest=null,dist=6;for(const c of cars){if(c.traffic)continue;const d=c.g.position.distanceTo(player.g.position);if(d<dist){dist=d;closest=c}}return closest}
 function advance(){mission++;cash+=mission===1?0:500;message(mission===1?'New objective · Head to the waterfront':mission===4?'Story complete · +$500 · Free roam unlocked':'Mission complete · +$500');}
 function interact(){if(paused)return;if(currentCar){if(Math.abs(currentCar.speed)>4){message('Slow down before stepping out');return}const c=currentCar;let placed=false;for(const side of [-1,1]){const x=c.g.position.x+Math.cos(c.g.rotation.y)*side*2.2,z=c.g.position.z-Math.sin(c.g.rotation.y)*side*2.2;if(!collision(x,z)){player.g.position.set(x,.28,z);placed=true;break}}if(!placed){message('Move to an open street to exit');return}player.g.visible=true;currentCar.speed=0;currentCar=null;}else{const c=nearest();if(c){currentCar=c;player.g.visible=false;yaw=c.g.rotation.y;if(mission===0)advance()}else message('Walk closer to a parked vehicle')}}
 function recover(){if(currentCar){currentCar.g.position.set(4,.08,33);currentCar.g.rotation.y=0;currentCar.speed=0;}else player.g.position.set(6.8,.28,33);vertical=jump=0;yaw=.24;message('Back on a safe street')}
 function keyDown(e){if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;if(e.code==='KeyE')interact();if(e.code==='KeyR'&&!paused)recover()}
 const keyUp=e=>keys.delete(e.code),blur=()=>{keys.clear();dragging=false};
 const pointerDown=e=>{dragging=true;lastX=e.clientX;lastY=e.clientY;renderer.domElement.setPointerCapture(e.pointerId)},pointerUp=()=>{dragging=false},pointerMove=e=>{if(!dragging||paused)return;yaw-=(e.clientX-lastX)*.006;pitch=THREE.MathUtils.clamp(pitch+(e.clientY-lastY)*.004,-.08,.8);lastX=e.clientX;lastY=e.clientY;dragTime=elapsed};
 window.addEventListener('keydown',keyDown);window.addEventListener('keyup',keyUp);window.addEventListener('blur',blur);renderer.domElement.addEventListener('pointerdown',pointerDown);renderer.domElement.addEventListener('pointerup',pointerUp);renderer.domElement.addEventListener('pointercancel',pointerUp);renderer.domElement.addEventListener('pointermove',pointerMove);
 const resize=()=>{const w=container.clientWidth,h=container.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()};resize();const observer=new ResizeObserver(resize);observer.observe(container);
 function drawMap(canvas,full=false){const ctx=canvas.getContext('2d');if(!ctx)return;const w=canvas.width,h=canvas.height,p=currentCar?currentCar.g.position:player.g.position,scale=full?Math.min(w,h)/550:1.15,cx=full?0:p.x,cz=full?0:p.z;const xx=x=>w/2+(x-cx)*scale,zz=z=>h/2+(z-cz)*scale;ctx.fillStyle='#183b43';ctx.fillRect(0,0,w,h);ctx.fillStyle='#273f3e';ctx.fillRect(xx(-248),zz(-248),496*scale,496*scale);ctx.fillStyle='#52625a';ctx.fillRect(xx(212),zz(-248),27*scale,496*scale);ctx.fillStyle='#9a9573';ctx.fillRect(xx(239),zz(-248),20*scale,496*scale);ctx.strokeStyle='#152d31';ctx.lineWidth=18*scale;for(const r of roads){ctx.beginPath();ctx.moveTo(xx(r),zz(-245));ctx.lineTo(xx(r),zz(245));ctx.stroke();ctx.beginPath();ctx.moveTo(xx(-245),zz(r));ctx.lineTo(xx(245),zz(r));ctx.stroke()}ctx.fillStyle='#3c5350';for(const c of colliders)ctx.fillRect(xx(c.x-c.w),zz(c.z-c.d),c.w*2*scale,c.d*2*scale);for(const c of cars){if(c.traffic)continue;ctx.fillStyle='#8fbec1';ctx.fillRect(xx(c.g.position.x)-2,zz(c.g.position.z)-2,4,4)}if(mission<4){const t=targets[mission];ctx.strokeStyle='#e7c06a';ctx.lineWidth=full?3:2;ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(xx(p.x),zz(p.z));ctx.lineTo(xx(p.x),zz(t.z));ctx.lineTo(xx(t.x),zz(t.z));ctx.stroke();ctx.setLineDash([]);const mx=Math.max(12,Math.min(w-12,xx(t.x))),mz=Math.max(14,Math.min(h-14,zz(t.z)));ctx.fillStyle='#f4cc6e';ctx.beginPath();ctx.arc(mx,mz,6,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff1b2';ctx.beginPath();ctx.arc(mx,mz,10,0,Math.PI*2);ctx.stroke()}ctx.save();ctx.translate(xx(p.x),zz(p.z));ctx.rotate(-(currentCar?currentCar.g.rotation.y:player.g.rotation.y));ctx.fillStyle='#fff';ctx.shadowColor='#fff';ctx.shadowBlur=8;ctx.beginPath();ctx.moveTo(0,-8);ctx.lineTo(5,5);ctx.lineTo(0,2);ctx.lineTo(-5,5);ctx.closePath();ctx.fill();ctx.restore();if(full){ctx.fillStyle='#b6c9c2';ctx.font='14px Arial';ctx.textAlign='center';ctx.fillText('DOWNTOWN',xx(-115),zz(-210));ctx.fillText('PALM DISTRICT',xx(40),zz(40));ctx.fillText('OCEANFRONT',xx(196),zz(-215));ctx.fillText('LIGHTHOUSE',xx(196),zz(195))}}
 let audioCtx=null,osc=null,gain=null,soundOn=false;
 function sound(on){soundOn=on;if(on&&!audioCtx){audioCtx=new AudioContext();osc=audioCtx.createOscillator();gain=audioCtx.createGain();osc.type='sawtooth';gain.gain.value=0;const filter=audioCtx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=230;osc.connect(filter);filter.connect(gain);gain.connect(audioCtx.destination);osc.start()}if(on)audioCtx?.resume();else if(gain)gain.gain.setTargetAtTime(0,audioCtx.currentTime,.1)}
 const clock=new THREE.Clock();
 function tick(){if(disposed)return;frameId=requestAnimationFrame(tick);const dt=Math.min(clock.getDelta(),.04);if(!paused){elapsed+=dt;waterMat.uniforms.time.value=elapsed;diamond.rotation.y+=dt;diamond.position.y=4+Math.sin(elapsed*2)*.25;const forward=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0),turn=(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)-(keys.has('KeyD')||keys.has('ArrowRight')?1:0),boost=keys.has('ShiftLeft')||keys.has('ShiftRight');
 if(currentCar){const c=currentCar;c.speed+=forward*dt*(boost?22:14);c.speed*=Math.exp(-dt*(keys.has('Space')?5:forward?.23:1));c.speed=THREE.MathUtils.clamp(c.speed,-12,boost?48:34);c.g.rotation.y+=turn*dt*1.7*Math.min(1,Math.abs(c.speed)/8)*Math.sign(c.speed||1);const nx=c.g.position.x-Math.sin(c.g.rotation.y)*c.speed*dt,nz=c.g.position.z-Math.cos(c.g.rotation.y)*c.speed*dt;if(!collision(nx,nz,1.3)){c.g.position.x=nx;c.g.position.z=nz}else{c.speed*=-.22;if(Math.abs(c.speed)>2)message('Easy on the paintwork!')}c.g.rotation.z=THREE.MathUtils.lerp(c.g.rotation.z,-turn*Math.abs(c.speed)*.0009,.1);if(!dragging&&elapsed-dragTime>1.5){yaw+=Math.atan2(Math.sin(c.g.rotation.y-yaw),Math.cos(c.g.rotation.y-yaw))*Math.min(1,dt*2.6)}player.g.position.copy(c.g.position);
 }else{let dx=-Math.sin(yaw)*forward-Math.cos(yaw)*turn,dz=-Math.cos(yaw)*forward+Math.sin(yaw)*turn;const len=Math.hypot(dx,dz);if(len){dx/=len;dz/=len;const speed=boost?8:4.1,nx=player.g.position.x+dx*speed*dt,nz=player.g.position.z+dz*speed*dt;if(!collision(nx,player.g.position.z))player.g.position.x=nx;if(!collision(player.g.position.x,nz))player.g.position.z=nz;const angle=Math.atan2(-dx,-dz);player.g.rotation.y+=Math.atan2(Math.sin(angle-player.g.rotation.y),Math.cos(angle-player.g.rotation.y))*Math.min(1,dt*12)}if(keys.has('Space')&&jump===0){vertical=6;jump=.001}if(jump>0){vertical-=16*dt;jump=Math.max(0,jump+vertical*dt)}player.g.position.y=.28+jump;player.arms.forEach((a,i)=>a.rotation.x=len?Math.sin(elapsed*(boost?13:9)+i*Math.PI)*.55:0);player.legs.forEach((a,i)=>a.rotation.x=len?Math.sin(elapsed*(boost?13:9)+i*Math.PI+Math.PI)*.6:0)}
 for(const c of cars)if(c.traffic){c.phase+=dt*7*c.dir;const t=((c.phase+240)%480+480)%480-240;const lane=c.route+(c.dir>0?-3.5:3.5);const nx=c.axis?t:lane,nz=c.axis?lane:t;if(Math.hypot(nx-player.g.position.x,nz-player.g.position.z)>5){c.g.position.set(nx,.08,nz);c.g.rotation.y=c.axis?(c.dir>0?-Math.PI/2:Math.PI/2):(c.dir>0?Math.PI:0)}else c.phase-=dt*7*c.dir}
 for(const p of people){p.g.position.z+=p.dir*p.speed*dt;if(Math.abs(p.g.position.z)>237)p.dir*=-1;p.g.rotation.y=p.dir>0?Math.PI:0;p.arms.forEach((a,i)=>a.rotation.x=Math.sin(elapsed*5+p.phase+i*Math.PI)*.35);p.legs.forEach((a,i)=>a.rotation.x=Math.sin(elapsed*5+p.phase+i*Math.PI+Math.PI)*.4)}
 const pos=currentCar?currentCar.g.position:player.g.position;if(mission>0&&mission<4&&pos.distanceTo(targets[mission])<9&&currentCar)advance();marker.visible=mission<4;if(mission<4)marker.position.copy(targets[mission]);
 const distance=currentCar?10:7.4;lookTarget.copy(pos).add(new THREE.Vector3(0,currentCar?1.5:1.6,0));cameraTarget.set(pos.x+Math.sin(yaw)*distance,pos.y+(currentCar?3.5:2.8)+pitch*7,pos.z+Math.cos(yaw)*distance); // Keep the follow camera outside solid buildings.
 for(let k=10;k>1;k--){const f=k/10,x=THREE.MathUtils.lerp(lookTarget.x,cameraTarget.x,f),z=THREE.MathUtils.lerp(lookTarget.z,cameraTarget.z,f);if(collision(x,z,.1)){cameraTarget.x=THREE.MathUtils.lerp(lookTarget.x,cameraTarget.x,(k-1)/10);cameraTarget.z=THREE.MathUtils.lerp(lookTarget.z,cameraTarget.z,(k-1)/10)}}
 camera.position.lerp(cameraTarget,1-Math.exp(-dt*7));camera.lookAt(lookTarget);sky.position.copy(camera.position);sun.position.set(pos.x-90,105,pos.z-110);sun.target.position.set(pos.x,0,pos.z);
 if(gain){gain.gain.setTargetAtTime(soundOn && currentCar && !paused ? (Math.abs(currentCar.speed)>1 ? .025 : .01) : 0,audioCtx.currentTime,.15);osc.frequency.setTargetAtTime(35+Math.abs(currentCar?.speed||0)*2.5,audioCtx.currentTime,.15)}
 if(elapsed-lastHud>.12){lastHud=elapsed;const minimap=document.getElementById('minimap');if(minimap)drawMap(minimap);onHud({speed:Math.round(Math.abs(currentCar?.speed||0)*3.6),cash,mission,distance:mission<4?Math.round(pos.distanceTo(targets[mission])):0,driving:!!currentCar,nearCar:!!nearest(),district:pos.x>175?'Oceanfront':pos.x<-55&&pos.z<-55?'Downtown':pos.z>138?'Lighthouse Point':'Palm District',message:elapsed<toastUntil?toast:'',time:'18:'+String(42+Math.floor(elapsed/60)%18).padStart(2,'0')})}
 }renderer.render(scene,camera)}
 tick();
 return {interact,recover,drawMap,sound,input:(key,value)=>{if(value)keys.add(key);else keys.delete(key)},pause:value=>{paused=value;keys.clear();if(value&&gain)gain.gain.setTargetAtTime(0,audioCtx.currentTime,.1)},dispose:()=>{disposed=true;cancelAnimationFrame(frameId);observer.disconnect();window.removeEventListener('keydown',keyDown);window.removeEventListener('keyup',keyUp);window.removeEventListener('blur',blur);renderer.domElement.removeEventListener('pointerdown',pointerDown);renderer.domElement.removeEventListener('pointerup',pointerUp);renderer.domElement.removeEventListener('pointercancel',pointerUp);renderer.domElement.removeEventListener('pointermove',pointerMove);audioCtx?.close();const gs=new Set(),ms=new Set(),ts=new Set();scene.traverse(o=>{if(o.geometry)gs.add(o.geometry);if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>{ms.add(m);if(m.map)ts.add(m.map)})});gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());ts.forEach(t=>t.dispose());renderer.dispose();renderer.domElement.remove()}};
}
